# https://gleam.run/writing-gleam/gleam-toml/.

name = "frontend"
target = "javascript"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.6.3 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.6.2 and < 2.0.0"
